#pragma once

#include <iostream>
#include <algorithm>
#include <map>
#include <unordered_map>
#include <array>
#include <string.h>
#include <fstream>
#include <math.h>
#include <cmath>
#include <thread>
#include <time.h>
#include <ctime>
#include <stdio.h>
#include <vector>
#include <queue>
#include <deque>
#include <sstream>